preload = /home/rbe/.config/hypr/CosmictClifstPrimary.jpg
preload = /home/rbe/.config/hypr/CosmictClifstExtended.jpg
#wallpaper = ,/home/rbe/.config/hypr/CosmictClifstExtended.jpg
wallpaper = eDP-1,/home/rbe/.config/hypr/CosmictClifstPrimary.jpg
wallpaper = DP-3,/home/rbe/.config/hypr/CosmictClifstPrimary.jpg
wallpaper = DP-4,/home/rbe/.config/hypr/CosmictClifstPrimary.jpg
wallpaper = DP-5,/home/rbe/.config/hypr/CosmictClifstExtended.jpg
wallpaper = DP-6,/home/rbe/.config/hypr/CosmictClifstPrimary.jpg
wallpaper = DP-7,/home/rbe/.config/hypr/CosmictClifstPrimary.jpg
wallpaper = DP-8,/home/rbe/.config/hypr/CosmictClifstPrimary.jpg
wallpaper = DP-9,/home/rbe/.config/hypr/CosmictClifstPrimary.jpg
wallpaper = DVI-I-1,/home/rbe/.config/hypr/CosmictClifstPrimary.jpg
wallpaper = HDMI-A-2,/home/rbe/.config/hypr/CosmictClifstPrimary.jpg
