preload = /home/rbe/.config/hypr/CosmictClifstPrimary.jpg
preload = /home/rbe/.config/hypr/CosmictClifstExtended.jpg

wallpaper {
	monitor = 
	path = /home/rbe/.config/hypr/CosmictClifstPrimary.jpg
}

wallpaper {
	monitor = DP-3
	path = /home/rbe/.config/hypr/CosmictClifstExtended.jpg
}
